name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.3.0
      with:
        xcode-version: '14.0'
    - name: Test 16
      run: xcodebuild -scheme Sworm-Package -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.0' clean test
