name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.3.0
      with:
        xcode-version: '13.2'
    - name: Test 15
      run: xcodebuild -scheme Sworm-Package -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' clean test
